dependencies:
  - python=3.12.11
  - pip
  - affine
  - cfgrib
  - dask>=2025.1 
  - dask-geopandas
  - dask-image
  - fiona
  - geopandas
  - netcdf4
  - numba
  - numpy
  - pandas
  - pyogrio
  - rasterio
  - rioxarray
  - scipy
  - shapely
  - xarray
  - ipywidgets
  - ipyleaflet
  - voila
  - raster-tools
